# wscript
top = "."
out = "build"


def options(opt):
    opt.load("compiler_cxx")


def configure(conf):
    conf.load("compiler_cxx")


def build(bld):
    # Source files
    softcut_src = [
        "../../lib/Chords.cpp",
    ]

    # Compile the library
    bld.objects(
        source=softcut_src,
        includes=[],
        target="softcut",
        cxxflags="-O2 -Wall",
    )

    # Compile main program
    bld.program(source="main.cpp", target="main", use="softcut", cxxflags="-O2 -Wall")
