name: build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.1
      - name: Install ncurses
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb && sudo dpkg -i libtinfo5_6.4-2_amd64.deb && rm -f libtinfo5_6.4-2_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.4-2_amd64.deb && sudo dpkg -i libncurses5_6.4-2_amd64.deb && rm -f libncurses5_6.4-2_amd64.deb
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y lib32ncurses5-dev libncurses5 libncurses5-dev 
      - name: Install gcc-arm-none-eabi-10
        run: |
          cd $HOME/bin
          wget https://github.com/schollz/daisy1/releases/download/prereqs/gcc-arm-none-eabi-10-2020-q4-major.zip
          unzip gcc-arm-none-eabi-10-2020-q4-major.zip
          rm gcc-arm-none-eabi-10-2020-q4-major.zip
